# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-17 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Question')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Theme')),
            ],
        ),
    ]
