# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-18 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180518_0918'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
