# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-18 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_question_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.CharField(default='Default', max_length=200),
            preserve_default=False,
        ),
    ]
